"""Add relationship for table user

Revision ID: 5e4b22877fff
Revises: e1649863dde8
Create Date: 2025-06-23 07:05:32.302628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4b22877fff'
down_revision: Union[str, Sequence[str], None] = 'e1649863dde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
