"""Add embedding column to contact_notes

Revision ID: 606bc3788ea8
Revises: 677e58ac8e82
Create Date: 2025-06-22 17:38:46.142446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '606bc3788ea8'
down_revision: Union[str, Sequence[str], None] = '677e58ac8e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_notes', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_notes', 'embedding')
    # ### end Alembic commands ###
